# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('promocion', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('color', models.CharField(default='#d898e8', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='ClasesPreguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('color', models.CharField(default='#d898e8', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('color', models.CharField(default='#d898e8', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.ClasesPreguntas')),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('promocion', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('color', models.CharField(default='#d898e8', max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clases.Familias')),
                ('preguntas', models.ManyToManyField(blank=True, to='clases.ClasesPreguntas')),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', models.CharField(max_length=100)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Productos'),
        ),
        migrations.AddField(
            model_name='clases',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='clases.ClasesPreguntas'),
        ),
        migrations.AddField(
            model_name='clases',
            name='productos',
            field=models.ManyToManyField(blank=True, to='clases.Productos'),
        ),
    ]
