# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='familia',
            new_name='familias',
        ),
    ]
