# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clases',
            options={'ordering': ('orden', 'id'), 'verbose_name': 'Clase'},
        ),
    ]
