# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20170907_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ('orden', 'nombre', 'familias')},
        ),
        migrations.RenameField(
            model_name='clases',
            old_name='preguntas',
            new_name='clasespreguntas',
        ),
        migrations.RenameField(
            model_name='preguntas',
            old_name='grupo',
            new_name='clasespreguntas',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='preguntas',
            new_name='clasespreguntas',
        ),
        migrations.AlterField(
            model_name='clases',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clases',
            name='promocion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='promocion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
