# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20170908_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='ignore',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
