# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_productos_ignore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clases',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'Clase'},
        ),
        migrations.AlterModelOptions(
            name='clasespreguntas',
            options={'verbose_name': 'Grupo Pregunta'},
        ),
        migrations.AlterModelOptions(
            name='familias',
            options={'verbose_name': 'Familia de productos'},
        ),
        migrations.AlterModelOptions(
            name='ingredientes',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'Ingrediente'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'Pregunta'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ('familias', 'orden', 'nombre'), 'verbose_name': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='sugerencias',
            options={'verbose_name': 'Sugerencia'},
        ),
    ]
