# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albaranes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripci\xf3n')),
                ('fecha_apunte', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('fecha_modificado', models.DateField(auto_now=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='albaranes')),
                ('aviso', models.CharField(blank=True, max_length=150, null=True, verbose_name='Aviso')),
                ('pagado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentasGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apunte', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('fecha_modificado', models.DateField(auto_now=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='facturas')),
                ('albaranes', models.ManyToManyField(to='contabilidad.Albaranes')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripci\xf3n')),
                ('fecha_apunte', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateField(auto_now=True)),
                ('pagado', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CuentasGastos')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(default='Caja del dia', max_length=50, verbose_name='Descripci\xf3n')),
                ('fecha', models.DateField()),
                ('fecha_apunte', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_apunte'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raz\xf3n social')),
                ('CIF', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direcci\xf3n')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoRegulador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_apunte', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Proveedores')),
            ],
            options={
                'ordering': ['-fecha_apunte'],
            },
        ),
        migrations.CreateModel(
            name='SubCuentaGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CuentasGastos')),
                ('gastos', models.ManyToManyField(to='contabilidad.Gastos')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='albaranes',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Proveedores'),
        ),
    ]
