# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaspedido',
            name='servido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='servido',
            field=models.BooleanField(default=False),
        ),
    ]
