# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numero_pedido', models.IntegerField()),
                ('modo_pago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(blank=True, default='no_arqueado', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pedidos Extra',
            },
        ),
        migrations.AlterModelOptions(
            name='arqueos',
            options={'verbose_name': 'Arqueo'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='direcciones',
            options={'verbose_name': 'Direccione'},
        ),
        migrations.AlterModelOptions(
            name='gastos',
            options={'verbose_name': 'Gasto'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido'},
        ),
        migrations.AlterField(
            model_name='conteo',
            name='can',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='texto_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='tipo',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tipo de moneda'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='des',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
