# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20170926_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteo',
            name='modify',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='modify',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='pedidosextra',
            name='estado',
            field=models.CharField(blank=True, default='no_arqueado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosextra',
            name='modo_pago',
            field=models.CharField(blank=True, default='Efectivo', max_length=50, null=True),
        ),
    ]
