# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20180301_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['-modify'], 'verbose_name': 'Pedido'},
        ),
        migrations.AddField(
            model_name='arqueos',
            name='pedidosextra',
            field=models.ManyToManyField(to='ventas.PedidosExtra'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
