# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ignore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=9)),
                ('incremento', models.CharField(max_length=25)),
                ('orden', models.IntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.GrupoPregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
                ('color', models.CharField(max_length=9)),
                ('precio', models.CharField(max_length=25)),
                ('impresora', models.CharField(max_length=50)),
                ('preguntas', models.ManyToManyField(to='productos.GrupoPregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
                ('color', models.CharField(max_length=9)),
                ('titulo', models.CharField(max_length=100)),
                ('promocion', models.CharField(max_length=10)),
                ('preguntas', models.ManyToManyField(to='productos.GrupoPregunta')),
                ('productos', models.ManyToManyField(to='productos.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='ignore',
            name='relMod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Preguntas'),
        ),
        migrations.AddField(
            model_name='ignore',
            name='relProd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Productos'),
        ),
    ]
